### ISSUE TITLE
Effectiveness Analysis Code

### ISSUE THREAD

**Issue by zyccyz** [YRdddream/attattr#2]
Hello,
It seems that there is no corresponding code for Effectiveness Analysis in Section 4.1. Would you be able to add it? Besides, I have a question about Section 4.1: The I_{h} selection principle is not clear in the paper, how do you calculate the importance of the head based on attr (max pool or avg pool)?

![image](https://user-images.githubusercontent.com/44648619/115640061-a835c100-a348-11eb-825e-8baf01a1d435.png)

**Comment by YRdddream** [comment]
Hi, we use max pool in Sec4.1. You can use this file attattr/prune_head_with_attr.py to reproduce Sec4.1 with few modifications. Just for every example, we prune the attention heads according to its golden label and record the accuracy. In other words, the pruning order are different for different examples in Sec4.1.
