### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Jxu-Thu** [YRdddream/attattr#4]
Thanks for your great codes! I enjoy reading the paper.

When reproducing results    following the provided readme,

python examples/attribution_tree.py --attr_file ${model_and_data}/mnli_example/attr_zero_base_exp16.json \
       --tokens_file ${model_and_data}/mnli_example/tokens_and_pred_100.json \
       --task_name mnli --example_index 16

 I encounter the bugs 

Traceback (most recent call last):
  File "examples/attribution_tree.py", line 145, in <module>
    main()
  File "examples/attribution_tree.py", line 98, in main
    with open(args.tokens_file) as fin:
IndexError: list index out of range

I found that the provided attribution json is 22*22 matrix, but the tokens of index 16 in tokens_and_pred_100.json only have 21 tokens. 

['[CLS]', 'the', 'emotions', 'are', 'raw', 'and', 'will', 'strike', 'a', 'nerve', 'with', 'anyone', 'who', "'", 's', 'ever', 'had', 'family', 'trauma', '.', '[SEP]']

Thus, it incurs the error.

Could you check the provided the files or codes? Or I missed something?

**Comment by zbszd04160408** [comment]
^^got the same issue as yours. Have you fixed it? @Jxu-Thu

**Comment by YRdddream** [comment]
Hi, I'm sorry that I put the wrong file "tokens_and_pred_100.json" on Google Drive, I have updated it. Please download and test it again. Thanks!

**Comment by zbszd04160408** [comment]
thanks!
