### ISSUE TITLE
Interval parameter m in paper

### ISSUE THREAD

**Issue by HireTheHero** [YRdddream/attattr#5]
Hi, 

Catching up with this repo together with your paper. Thanks for providing great attribution methodology.
In 3rd/4th pages of [your paper](https://arxiv.org/pdf/2004.11207.pdf), found a description of `approximation step parameter m`, which I couldn't find the way to tune yet.

Could you point out the line of the codes you're setting it, or could you guide me a bit so that I can implement on my own?

Thanks!

**Comment by YRdddream** [comment]
Hi,

In examples/prune_head_with_attr.py and examples/generate_attrscore.py, the variable "num_points" (num_points = batch_size * num_batch) represents the approximation step. You can change batch_size and num_batch to tune it.
