### ISSUE TITLE
attention tree threshold

### ISSUE THREAD

**Issue by gauneg** [YRdddream/attattr#9]
Hi, great work. I was trying to understand the code for the attribute tree construction.
When calculating  $max(Attr(A^t))$, why do you leave out the values of the 0th row. In the following section:

```python
proportion_all = copy.deepcopy(att_all)
for i in range(len(proportion_all)):
    proportion_all[i] /= abs(proportion_all[i][1:,:].max())

```
Why not use all the parameters to calculate the max? Is it a part of the heuristics of removing the interaction with the [CLS] token?

**Comment by YRdddream** [comment]
Yes, because [CLS] token is the root of the attribution tree so we only consider its interactions with other tokens in the last layer.
